pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Starting build...'

                sh '''
                    cd "$WORKSPACE/CI-CD/Jenkins/Day1/practice/hello-jenkins"
                    chmod +x app.sh
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'

                sh '''
                    cd "$WORKSPACE/CI-CD/Jenkins/Day1/practice/hello-jenkins"
                    ./app.sh
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment stage completed.'
            }
        }
    }
}
